# backend_part

Yes it helped.
But now it says 
fastapi_app  |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 876, in __connect_addr                                                                                                             
fastapi_app  |     await connected                                                                                                                                                                                                
fastapi_app  | asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "admin"   
at the same time i'm using variables from .env file everywhere so, i'm loosing it, how it's possible

